#!/bin/bash
cp -vf /home/jmurin/.m2/repository/me/dm7/barcodescanner/zbar/1.8.4/jni/arm64-v8a/libzbarjni.so /home/jmurin/Desktop/bakalarka/app/OpencvApp4/app/src/main/jniLibs/arm64-v8a
cp -vf /home/jmurin/.m2/repository/me/dm7/barcodescanner/zbar/1.8.4/jni/armeabi/libzbarjni.so /home/jmurin/Desktop/bakalarka/app/OpencvApp4/app/src/main/jniLibs/armeabi
cp -vf /home/jmurin/.m2/repository/me/dm7/barcodescanner/zbar/1.8.4/jni/armeabi-v7a/libzbarjni.so /home/jmurin/Desktop/bakalarka/app/OpencvApp4/app/src/main/jniLibs/armeabi-v7a
cp -vf /home/jmurin/.m2/repository/me/dm7/barcodescanner/zbar/1.8.4/jni/mips/libzbarjni.so /home/jmurin/Desktop/bakalarka/app/OpencvApp4/app/src/main/jniLibs/mips
cp -vf /home/jmurin/.m2/repository/me/dm7/barcodescanner/zbar/1.8.4/jni/mips64/libzbarjni.so /home/jmurin/Desktop/bakalarka/app/OpencvApp4/app/src/main/jniLibs/mips64
cp -vf /home/jmurin/.m2/repository/me/dm7/barcodescanner/zbar/1.8.4/jni/x86/libzbarjni.so /home/jmurin/Desktop/bakalarka/app/OpencvApp4/app/src/main/jniLibs/x86
cp -vf /home/jmurin/.m2/repository/me/dm7/barcodescanner/zbar/1.8.4/jni/x86_64/libzbarjni.so /home/jmurin/Desktop/bakalarka/app/OpencvApp4/app/src/main/jniLibs/x86_64

